version: "3.7"
services:
  backend:
  container_name: backend
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - 3001:5001
  networks:
    - processor-net
  martin:
    container_name: martin
    image:

networks:
  processor-net:
    driver: bridge


    volumes:
      martin-volumen